// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllAdver: typeof import('./../src/components/allAdver/index.vue')['default']
    BackAdver: typeof import('./../src/components/backAdver/index.vue')['default']
    BagBoxRule: typeof import('./../src/components/bagBoxRule/index.vue')['default']
    CompanyInfo: typeof import('./../src/components/companyInfo/index.vue')['default']
    CountDown: typeof import('./../src/components/CountDown/index.vue')['default']
    CustomPopAd: typeof import('./../src/components/customPopAd/index.vue')['default']
    Danmu: typeof import('./../src/components/danmu/index.vue')['default']
    Firework: typeof import('./../src/components/Firework/index.vue')['default']
    GoodsList: typeof import('./../src/components/goodsList/index.vue')['default']
    Loading: typeof import('./../src/components/loading/index.vue')['default']
    MaskMod: typeof import('./../src/components/maskMod/index.vue')['default']
    PayMethod: typeof import('./../src/components/PayMethod/index.vue')['default']
    PopupArg: typeof import('./../src/components/popupArg/index.vue')['default']
    RedSideBar: typeof import('./../src/components/redSideBar/index.vue')['default']
    RetentionPopup: typeof import('./../src/components/retentionPopup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../src/components/sideBar/index.vue')['default']
    SideBarActivity: typeof import('./../src/components/sideBarActivity/index.vue')['default']
    TuiAd: typeof import('./../src/components/TuiAd/index.vue')['default']
    UserBook: typeof import('./../src/components/UserBook/index.vue')['default']
    WriteSideBar: typeof import('./../src/components/writeSideBar/index.vue')['default']
  }
}
