export const goodsList: any[] = [
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/aiqyishipin.jpg',
    goodName: '爱奇艺黄金会员12个月',
    id: 1,
    level: 1,
    price: 299,
    levelName: '至尊款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/tengxunshipin.jpg',
    goodName: '腾讯视频VIP12个月',
    id: 2,
    level: 1,
    price: 253,
    levelName: '至尊款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/youkushipin.jpg',
    goodName: '优酷视频VIP12个月',
    id: 3,
    level: 1,
    price: 198,
    levelName: '至尊款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/mangguoshipin.jpg',
    goodName: '芒果TVPC移动影视会员12个月',
    id: 4,
    level: 1,
    price: 198,
    levelName: '至尊款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/kugouyinyue.jpg',
    goodName: '酷狗音乐豪华会员12个月',
    id: 5,
    level: 1,
    price: 180,
    levelName: '至尊款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/aiqyishipin.jpg',
    goodName: '爱奇艺黄金会员6个月',
    id: 6,
    level: 2,
    price: 149,
    levelName: '稀有款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/tengxunshipin.jpg',
    goodName: '腾讯视频VIP6个月',
    id: 7,
    level: 2,
    price: 138,
    levelName: '稀有款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/youkushipin.jpg',
    goodName: '优酷视频VIP6个月',
    id: 8,
    level: 2,
    price: 108,
    levelName: '稀有款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/mangguoshipin.jpg',
    goodName: '芒果TVPC移动影视会员6个月',
    id: 9,
    level: 2,
    price: 108,
    levelName: '稀有款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/aiqyishipin.jpg',
    goodName: '爱奇艺黄金会员3个月',
    id: 10,
    level: 3,
    price: 99,
    levelName: '惊喜款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/tengxunshipin.jpg',
    goodName: '腾讯视频VIP3个月',
    id: 11,
    level: 3,
    price: 68,
    levelName: '惊喜款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/youkushipin.jpg',
    goodName: '优酷视频VIP3个月',
    id: 12,
    level: 3,
    price: 69,
    levelName: '惊喜款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/mangguoshipin.jpg',
    goodName: '芒果TVPC移动影视会员3个月',
    id: 13,
    level: 3,
    price: 55,
    levelName: '惊喜款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/aiqyishipin.jpg',
    goodName: '爱奇艺黄金会员1个月',
    id: 14,
    level: 4,
    price: 40,
    levelName: '超值款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/tengxunshipin.jpg',
    goodName: '腾讯视频VIP1个月',
    id: 15,
    level: 4,
    price: 40,
    levelName: '超值款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/youkushipin.jpg',
    goodName: '优酷视频VIP1个月',
    id: 16,
    level: 4,
    price: 40,
    levelName: '超值款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/meituan.jpg',
    goodName: '美团单车会员月卡',
    id: 17,
    level: 4,
    price: 30,
    levelName: '超值款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/bilibili.jpg',
    goodName: '哔哩哔哩会员1个月',
    id: 18,
    level: 4,
    price: 40,
    levelName: '超值款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/ruixing.jpg',
    goodName: '瑞幸咖啡饮品券32元',
    id: 19,
    level: 4,
    price: 32,
    levelName: '超值款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/Da0090.jpg',
    goodName: 'MINISO露营唐老鸭趴姿坐姿公仔',
    id: 20,
    level: 4,
    price: 59,
    levelName: '超值款',
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/Da0094.jpg',
    goodName: 'MINISO非人哉之非人青春学院系列抱枕(哪吒)',
    id: 21,
    level: 4,
    price: 59,
    levelName: '超值款',
  },
];

export const bottomList: any[] = [
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/aiqyishipin.jpg',
    goodName: '爱奇艺黄金会员12个月',
    id: 1,
    level: 1,
    price: 299,
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/aiqyishipin.jpg',
    goodName: '爱奇艺黄金会员6个月',
    id: 2,
    level: 2,
    price: 149,
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/aiqyishipin.jpg',
    goodName: '爱奇艺黄金会员3个月',
    id: 3,
    level: 3,
    price: 99,
  },
  {
    goodImg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/aiqyishipin.jpg',
    goodName: '爱奇艺黄金会员1个月',
    id: 4,
    level: 4,
    price: 40,
  },
];

export const prizeList: any[] = [
  'https://html.sccdyzl.com/vue-cps/bagBoxPrize/good1.png',
  'https://html.sccdyzl.com/vue-cps/bagBoxPrize/good2.png',
  'https://html.sccdyzl.com/vue-cps/bagBoxPrize/good3.png',
  'https://html.sccdyzl.com/vue-cps/bagBoxPrize/good4.png',
  'https://html.sccdyzl.com/vue-cps/bagBoxPrize/good5.png',
  'https://html.sccdyzl.com/vue-cps/bagBoxPrize/good6.png',
  'https://html.sccdyzl.com/vue-cps/bagBoxPrize/good7.png',
  'https://html.sccdyzl.com/vue-cps/bagBoxPrize/good8.png',
  'https://html.sccdyzl.com/vue-cps/bagBoxPrize/good9.png',
];
export const levelList: any[] = [
  {
    id: 1,
    level: 1,
    levelName: '至尊款',
    probability: '0.008%',
    levelBg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/lv1.png',
  },
  {
    id: 2,
    level: 2,
    levelName: '稀有款',
    probability: '0.006%',
    levelBg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/lv2.png',
  },
  {
    id: 3,
    level: 3,
    levelName: '惊喜款',
    probability: '0.925%',
    levelBg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/lv3.png',
  },
  {
    id: 4,
    level: 4,
    levelName: '超值款',
    probability: '99.061%',
    levelBg: 'https://html.sccdyzl.com/vue-cps/bagBoxPrize/lv4.png',
  },
];
